language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
before_script:
  - rustup component add clippy
cache: cargo
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --verbose
  - cargo test --verbose
